"""empty message

Revision ID: cdf7ef81d6e1
Revises: 0306d2049892
Create Date: 2020-03-25 14:48:58.757367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf7ef81d6e1'
down_revision = '0306d2049892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tweet_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'latest_tweet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latest_tweet_id', sa.BIGINT(), nullable=True))
    op.drop_column('users', 'tweet_count')
    # ### end Alembic commands ###
